### ISSUE TITLE
Step functions, Data science sdk, metric definitions from estimator not working?

### ISSUE THREAD

**Issue by R4ZZ3** [awslabs/amazon-sagemaker-examples#1296]
How to pass metric definitions correctly to get those tracked to Sagemaker training job metrics?
I have the exact same setup working with normal training job ie not with step functions.

So this works
![image](https://user-images.githubusercontent.com/25264037/85681821-58f51480-b6d4-11ea-80f2-a04d3bdb523c.png)

Metrics are correctly defined:
![image](https://user-images.githubusercontent.com/25264037/85681866-65796d00-b6d4-11ea-9b13-76dcb8646649.png)

And are visible after training:
![image](https://user-images.githubusercontent.com/25264037/85681885-6a3e2100-b6d4-11ea-982a-487390917ae6.png)

Same definitions with Step functions:
![image](https://user-images.githubusercontent.com/25264037/85681920-732ef280-b6d4-11ea-82cf-539925cdf4de.png)

Metrics not visible:
![image](https://user-images.githubusercontent.com/25264037/85681943-79bd6a00-b6d4-11ea-8221-c006aa9c1825.png)

**Comment by vaib-amz** [comment]
Hi @R4ZZ3,

Thanks for reporting this. I believe this should have been fixed in this PR: https://github.com/aws/sagemaker-python-sdk/pull/1453 , which is a part of the 1.56.2 release of the SageMaker Python SDK: https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.56.2 . Could you please verify if the version of the SageMaker Python SDK you are using is >= 1.56.2? 

Thanks

**Comment by R4ZZ3** [comment]
Thanks for answering @vaib-amz 

I will check this probably next monday or tuesday.

**Comment by R4ZZ3** [comment]
@vaib-amz  That was the case.
I got it working today.
Thanks! :) Closing issue
