### ISSUE TITLE
scikit_bring_your_own.ipynb not working as expected

### ISSUE THREAD

**Issue by hantingxie** [awslabs/amazon-sagemaker-examples#195]
Hello,

## Background
I'm trying to learn how to create own containers and deploy a model with them. I have been following the example [scikit_bring_your_own.ipynb](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb) to push the docker image to my ECR repositories, train and upload the model artifact to S3 bucket. The Dockerfile was not changed, so the docker image should be the same. The model was successfully trained with the given codes.

## Error
However, when I'm trying to create the model from the container image and artifact (step "Deploy the model" in the notebook) by running:

from sagemaker.predictor import csv_serializer
predictor = tree.deploy(1, 'ml.m4.xlarge', serializer=csv_serializer)

I encountered an error which is:
`An error occurred (ValidationException) when calling the CreateModel operation: ECR image "xxxxxx(my account id here).dkr.ecr.us-west-2.amazonaws.com/decision-trees-sample" is invalid.`

## Attempts:

- I have tested hosting the model locally with the given train.sh, serve.sh and predict.sh files, the model works well locally.
- I have tried to use the SageMaker console to create the model from ECR, the error is the same
- I have tried to use AWS CLI to create the model, same issue.

Could anyone help with this problem?
Thanks a lot!

**Comment by djarpin** [comment]
Hi @hantingxie .
Sorry to hear about this problem, but thank you very much for bringing it to our attention.  We're still digging a bit more into this, but for the time being, if you add the container image tag ":latest", it should work.

We just merged a [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/196) to correct for this.  Note, we actually added the ":latest" tag to the estimator.  That's because `.deploy`, which calls CreateModel, uses the same image string by default as what's provided to the estimator.  CreateTrainingJob succeeds with or without the tag, so it's easy to add it there.  But, you could also add it as an `image='xxxxxx(my account id here).dkr.ecr.us-west-2.amazonaws.com/decision-trees-sample:latest'` argument to `.deploy`.

I'll close this issue for now, but please re-open if you end up running into any other problems.  Thanks!
