### ISSUE TITLE
scikit_bring_your_own.ipynb deploy model error

### ISSUE THREAD

**Issue by AirWrek** [awslabs/amazon-sagemaker-examples#197]
When going through the notebook above with a sagemaker notebook instance everything worked up to the deploy line:
`predictor = tree.deploy(1, 'ml.m4.xlarge', serializer=csv_serializer)`
There I get "ClientError: An error occurred (ValidationException) when calling the CreateModel operation: ECR image "<myaccount>.dkr.ecr.us-east-1.amazonaws.com/decision-trees-sample" is invalid."

I tried via the sagemaker console using my root account and also get the same ValidationException error.

Testing the image (pulled from ECR) locally with serve_local.sh/predict_local.sh didn't show errors

**Comment by djarpin** [comment]
Thanks, @AirWrek .  This looks like the same error that was raised [here](https://github.com/awslabs/amazon-sagemaker-examples/issues/195) and was fixed in this [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/196).  Sorry, I probably should have left the issue open a little longer for visibility.

The changes to the example notebooks in GitHub won't immediately cascade back to your SageMaker Notebook Instance, so you'll need to grab the updated version from here (or just add the ":latest" tag to the image argument in your estimator or deploy method).

Thanks!
