### ISSUE TITLE
where can I find gluon_recsys.ipynb

### ISSUE THREAD

**Issue by wei765** [awslabs/amazon-sagemaker-examples#209]
I saw the video Diving Deeper with Amazon SageMaker in the developer resources https://aws.amazon.com/sagemaker/developer-resources/?nc1=h_ls, the recommendation demo is very interesting, where can I find the code gluon_recsys.ipynb and gluon_recommender_system_webinar.ipynb?

**Comment by djarpin** [comment]
Thanks for your interest @wei765 !

We're still putting the finishing touches on the gluon recommender system notebook presented in that webinar (we want to provide a bit more context so that it makes sense as a standalone notebook).  In the meantime, much of the content in that notebook is based on a re:Invent 2017 presentation.  The slides for that are [here](https://www.slideshare.net/AmazonWebServices/building-content-recommendation-systems-using-apache-mxnet-and-gluon-mcl402-reinvent-2017).  Hope that helps.

**Comment by djarpin** [comment]
It took a bit longer than we'd like to get to this, but the Gluon recommender system notebook has been checked-in with this [PR](https://github.com/awslabs/amazon-sagemaker-examples/pull/218).  Thanks!
