### ISSUE TITLE
Deploying code from notebook

### ISSUE THREAD

**Issue by smartinio** [awslabs/amazon-sagemaker-examples#240]
From scikit_bring_your_own.ipynb
> When you are using a framework (such as Apache MXNet or TensorFlow) that has direct support in SageMaker, you can simply supply the Python code that implements your algorithm using the SDK entry points for that framework.

What exactly is this referring to? I have a python script currently living inside an .ipynb in Jupyter, SageMaker. It's a batch script which pulls the training data from DynamoDB and runs ALS training on it using Spark's MLLib. It finishes by writing some results to DynamoDB. Can I go ahead and deploy this as a recurring batch job easily without messing with docker containers?

**Comment by djarpin** [comment]
Hi @smartinkth .  Currently the Apache MXNet and TensorFlow are the only two frameworks with direct support in Amazon SageMaker.  The method of supplying Python code for those two frameworks is detailed [here](https://github.com/aws/sagemaker-python-sdk#mxnet-sagemaker-estimators).  That's independent of the use case you mentioned of scheduling a recurring job that uses Spark and DynamoDB.

Is there a reason you feel like you need a Docker container for this?  i.e. At it's simplest, could you just convert the .ipynb file to a .py script and schedule it to run as a cron job?

**Comment by smartinkth** [comment]
@djarpin Hi and thanks for the reply. Converting to a .py and scheduling as a cron sounds great, but I'm not exactly sure how I'd do that. Where do I deploy this... Lambda? How do I make sure Spark is available to the script? How do I know it uses distributed computing for the heavy lifting? Sorry if these are stupid questions!

**Comment by djarpin** [comment]
Hi @smartinkth .  It sounds like you're running the Spark job locally in your notebook instance, rather than with an EMR cluster, right?  I had originally assumed you were using a persistent EMR cluster but orchestrating from a small notebook instance.

If you are building the model in your notebook, then the simple cron job option probably requires you to keep your notebook instance on all the time, which may not be what you're looking for, particularly if your notebook instance is large and costly.

If you wanted to be able to run the job in SageMaker on a recurring basis in a managed setting (i.e. where the hardware is started and stopped for you when your job is done), then you probably would want to go the Docker container + SageMaker Training route.  There may be alternative solutions, but they are likely to require even more engineering.

Thanks.

**Comment by djarpin** [comment]
Closing for now.  Feel free to re-open if you have additional question.
