### ISSUE TITLE
Sagemaker Error

### ISSUE THREAD

**Issue by veerendarbokka** [awslabs/amazon-sagemaker-examples#559]
I am having this error. even though I have recreated the endpoint . still the same. 
 File "/home/ec2-user/.local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ec2-user/.local/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationError: An error occurred (ValidationError) when calling the InvokeEndpoint operation: Endpoint driving-endpoint of account 127310796078 not found.

**Comment by laosunhust** [comment]
Sagemaker engineer here. 

Since no exact date, region and requestID was provided, I did a search in a few of our largest regions, and in us-west-2 region and found that there was a call to DeleteEndpoint at January 5th 2019, 18:19:06.228 to the endpoint listed above for the account in the question body. 

Therefore, the endpoint seems to have been deleted by the time you tried to invoke. Which notebook did you follow to create the endpoint? sometimes notebooks have a delete command at the end to prevent wasting your money after testing.

**Comment by ChoiByungWook** [comment]
Please reopen or create a new issue if this problem persists.

Thanks!
