### ISSUE TITLE
scikit bring your own - error in training model

### ISSUE THREAD

**Issue by arjunpn90** [awslabs/amazon-sagemaker-examples#571]
Hello @djarpin

I am trying to run the scikit BYO without changing anything and I get this error when I am trying to fit the model. Cloudwatch logs show just "/usr/bin/env: 'python\r': No such file or directory"

![image](https://user-images.githubusercontent.com/25255955/51344462-b38d4880-1abe-11e9-99f5-c7d66b89ee13.png)

Can you please help?

**Comment by madhurkgp** [comment]
@arjunpn90  - Hi, I'm facing the same issue, can you please elaborate your above solution.

**Comment by arjunpn90** [comment]
Hi @madhurkgp , 
The python version of the pickled code and python version in docker image should be same. 
I built the model using python 3.6 and version in docker image was 2.7 and the issue was resolved when the python version in docker image was changed to 3.6 as well.

**Comment by jamerico** [comment]
To any people that may be suffering in the future:

The problem is that the python script that contains the shelbeg command 
`#!/usr/bin/env python`

Was written with the Windows end of life (CRLF) and is being executed with the Unix end of life (LF) in Sagemaker.

Convert that file to the LF format and everything will work.

Thank me later.

**Comment by herley-shaori** [comment]
@jamerico Thank you so much. It happened to me, and I followed your solution. Here iss what I've done:
1. Install dos2unix.
2. Convert wsgi.py, train, serve, predictor.py from CRLF to LF.
