### ISSUE TITLE
scikit_bring_your_own - local_train script is failing

### ISSUE THREAD

**Issue by prasadpande1990** [awslabs/amazon-sagemaker-examples#744]
Hi, 

I am trying to run scikit_bring_your_own decision tree algorithm in my environment. But while running the local_train.sh, I am running into the following error -

```
container_linux.go:247: starting container process caused "exec: \"train\": executable file not found in $PATH"
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"train\\\": executable file not found in $PATH\"\n".
```
I have exactly same files structure as mentioned here.

Let me know what is going wrong in my case.

Thank You,
Prasad

**Comment by nery** [comment]
I've run into this issue inadvertently because in our own implementation we have multiple build stages in our `Dockerfile` and have a dedicated `sagemaker` user and group rather than running as just `root`(AWS should avoid this practice).

As for your case, the error is usually a result of the `${PATH}` file being set incorrectly, or the user  not having execution permissions on `train` and `serve`.

To solve the issue make sure you have the following set in your `Dockerfile`:

```docker
ENV PATH="/opt/program:${PATH}"
```
additionally 
```docker
RUN chmod +x /opt/program/train
RUN chmod +x /opt/program/serve
```

Hopefully this helps
