### ISSUE TITLE
Cannot find libcuda.so.1 when creating endpoint

### ISSUE THREAD

**Issue by yyc9268** [awslabs/amazon-sagemaker-examples#758]
Hi. I am struggling to make our object detection model available to use GPU instance on sagemaker.
We built our own pretrained model and packaged it in docker image. The problem occurs when creating endpoint using it. If i designate the EC2 instance as GPU(ml.p3.2xlarge), it produces following error.
<pre><code>tensorflow_model_server: error while loading shared libraries: libcuda.so.1</code></pre>
**Everything works fine on CPU based EC2 instances(ml.m4.xlarge).**
I accessed the endpoint on our local PC and got a proper response from endpoint.

We followed blog post to build a docker image ("https://medium.com/ml-bytes/how-to-create-a-tensorflow-serving-container-for-aws-sagemaker-4853842c9751").
We didn't use tf.estimator but converted our pre-trained model to tensorflow-serving compatible type as below.
![image](https://user-images.githubusercontent.com/17124362/59078320-8b8d6d00-8919-11e9-8eb7-05b0c559efb3.png)
We designated input and output in the code.
It is confirmed that the AWS endpoint receive input and return output as defined in the code above when using 'ml.m4.xlarge' instance.
We built the docker image using this create **model** and **Dockerfile** and **nginx.conf** (No python files using tf.estimator). 
The aforementioned error doesn't occur in setting,
<pre><code> 'FROM tensorflow/serving' in  Dockerfile
and designating EC2 instance as 'ml.m4.xlarge'
</code></pre>
But, if we change the setting to
<pre><code>'FROM tensorflow/serving:latest-gpu' or 'FROM tensorflow/serving:latest-devel-gpu' in dockerfile
and designate EC2 instance as 'ml.p3.2xlarge'
</code></pre>
libcuda.so.1 occur when creating endpoint
Also, we found that when we run docker image in our PC using **nvidia-docker**, it works fine with GPU but running with conventional docker fails with same error(libcuda.so.1 cannot be found)

It is very confusing that why AWS sagemaker cannot assign libcuda.so.1 to our endpoint and fails.
Doesn't it run the ECR image using nvidia-docker? Then how could I fix this problem?
I hope there are a few experts who can answer this problem.

Thanks!

**Comment by nasehim7** [comment]
@yyc9268 It seems that the C shared object in the error is not in the environment while trying to use the GPU. It works fine for the usual - only CPU instances as the presence of the same object is not checked. Could you try using the docker files here: 

https://github.com/aws/sagemaker-tensorflow-serving-container/tree/master/docker

They should work fine

**Comment by yijieqiu** [comment]
First of all, you want to use `tensorflow/serving:latest-gpu` as base image, instead of the development image `tensorflow/serving:latest-devel-gpu`. The later includes the complete CUDA source and tool chain and might lead to unexpected dependency resolution problems when the model container runs on SageMaker. SageMaker [public documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-inference-code.html) explicitly calls out: "Don't bundle NVIDIA drivers with the image" when using BYO models with GPU instances.

In addition, depending on when your image was built, it might have resolved to a different release of TF serving container. The latest release [uses CUDA 10](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.gpu#L19), whereas the 1.12 release [uses CUDA 9](https://github.com/tensorflow/serving/blob/r1.12/tensorflow_serving/tools/docker/Dockerfile.gpu#L19). You might run into issues if your inference code is compatible with one version of CUDA but not the other.

**Comment by yyc9268** [comment]
@nasehim7 Yes. This is exactly the right solution for me. Endpoint was successfully created with the Dockerfile in link. thanks.

@yijieqiu It is a new information for me that NVIDIA drivers shouldn't be included in image. So your guess is that tf-serving container version and CUDA version may not be compatible in our build. We are currently inspecting why ours work with @nasehim7 solution. Your answer would be great help!
