### ISSUE TITLE
tensorflow_script_mode_horovod. Local mode. What's the meaning of instance_count = 2?

### ISSUE THREAD

**Issue by sermolin** [awslabs/amazon-sagemaker-examples#761]
When we set train_instance_type='local', we still set instance_count = 2. Since we are training on a local machine, shouldn't it be set to 1? I tried removing train_instance_count from the estimator and got an error.

**Comment by nasehim7** [comment]
Seems like the instance count is somewhere not taken into account or at the backend is set to 1 for local mode. However, setting of train_instance_count to value greater than 1 should throw some exception ideally:

CreateTraining job in local mode:
https://github.com/aws/sagemaker-python-sdk/blob/397fb90eda37daaede5593bbd43453e5893e22ac/src/sagemaker/local/local_session.py#L55

has this line in it
container = _SageMakerContainer(ResourceConfig['InstanceType'], ResourceConfig['InstanceCount'],
                                        AlgorithmSpecification['TrainingImage'], self.sagemaker_session)

which considers instance count in the ResourceConfig. Instance type is fine but why the instance count for local mode.

local session: https://github.com/aws/sagemaker-python-sdk/blob/1a0ed3f229805ed730cf4a77f315d35cc1a7769a/src/sagemaker/local/image.py#L54

Here in the Estimator.py for SageMaker:

https://github.com/aws/sagemaker-python-sdk/blob/686569e3e4fef9cbf8ad571a1499417a26e7dc90/src/sagemaker/estimator.py#L121

where we keep a check on number of instances in local mode for distributed training. Will it be good to implement something same for this one as well?

**Comment by jesterhazy** [comment]
@sermolin, thanks for using sagemaker!

Local mode launches your training containers on your computer using docker. If `instance_count` is 2, then you will get a local training "cluster" of two docker containers, both running on your computer. This is intentional and is meant to let you test your distributed training code locally before you run it in a real SageMaker training job.

Closing this issue as answered.
