### ISSUE TITLE
Random Cut Forest example errors

### ISSUE THREAD

**Issue by joshrodgersemn** [awslabs/amazon-sagemaker-examples#899]
Using SageMaker Jupyter notebook example: random_cut_forest.ipynb

Under inference section, I am receiving the error below - nothing has been changed in the example outside of setting the S3 bucket and prefix:

Error:

rcf_inference = rcf.deploy(
    initial_instance_count=1,
    instance_type='ml.m4.xlarge',
)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-42-a849c6b5231f> in <module>()
      1 rcf_inference = rcf.deploy(
      2     initial_instance_count=1,
----> 3     instance_type='ml.m4.xlarge',
      4 )

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in deploy(self, initial_instance_count, instance_type, accelerator_type, endpoint_name, use_compiled_model, update_endpoint, wait, model_name, kms_key, **kwargs)
    549         else:
    550             kwargs["model_kms_key"] = self.output_kms_key
--> 551             model = self.create_model(**kwargs)
    552         model.name = model_name
    553         return model.deploy(

**TypeError: create_model() got an unexpected keyword argument 'model_kms_key'**

**Comment by windhamg** [comment]
It appears that this has been fixed in the 1.42.8 branch of https://github.com/aws/sagemaker-python-sdk (see https://github.com/aws/sagemaker-python-sdk/pull/1081), but has not made it into the Sagemaker Jupyter notebook build yet.

What I did to work around this was to add a step at the beginning of this notebook (before the first `import sagemaker` : 
`! pip install --upgrade sagemaker==1.42.8`

**Comment by joshrodgersemn** [comment]
Awesome, thanks for the info!
