### ISSUE TITLE
PyTorch Captum Insights

### ISSUE THREAD

**Issue by austinmw** [awslabs/amazon-sagemaker-examples#908]
When I try to run PyTorch's new Captum Insights from a sagemaker notebook terminal on port 6006, the `/proxy/6006/` shows "Captum Insights" in browser tab name, but the web page is blank. The same method works fine on my local system.

<img width="1238" alt="Screenshot 2019-10-24 05 16 27" src="https://user-images.githubusercontent.com/12224358/67471474-780b4600-f61d-11e9-8e54-d9fc861f7ce5.png">

----
I used port 6006 because it seemed to work for TensorBoard previously. I also upgraded my conda `pytorch_p36` environment to torch==1.3.0, and installed Captum from source. I think it's a SageMaker issue, because it works fine locally.

**Comment by neelamgehlot** [comment]
Hi @austinmw,

Could you provide steps to reproduce?

Thanks,
Neelam

**Comment by neelamgehlot** [comment]
Hi @austinmw,

I was able to reproduce this issue. I looked at network logs and Jupyter logs on the Notebook Instance.

From network logs, the first GET request was successful that returned a HTML response without any HTML content, it only had JavaScript file reference. So Jupyter made more request to get those JavaScript files but those request failed with 404 because the file reference is with absolute path.
```
<link href="/static/css/main.a289dc29.chunk.css" rel="stylesheet">
<script src="/static/js/2.36da730b.chunk.js"></script>
<script src="/static/js/main.e8d30be4.chunk.js"></script>
```

The reason you can see "Captum Insights" in the browser tab name because that's part of HTML response returned in first GET request.

In this case Jupyter and proxy extensions are working as designed.

Please let us know if there is anything else we can help with.

Thanks,
Neelam

**Comment by neelamgehlot** [comment]
Related issue https://github.com/pytorch/captum/issues/138

**Comment by austinmw** [comment]
@neelamgehlot is there any workaround or does that mean it's going to stay incompatible with sagemaker?

**Comment by neelamgehlot** [comment]
@austinmw Unfortunately I am not aware of any workaround for this. I have provided steps to reproduce with local Jupyter installation on this issue https://github.com/pytorch/captum/issues/138 .
