### ISSUE TITLE
 scikit_bring_your_own: Error for Training job sagemaker-decision-trees-2020-01-04-14-39-17-942: Failed. Reason: AlgorithmError: Exit Code: 127

### ISSUE THREAD

**Issue by starrylive** [awslabs/amazon-sagemaker-examples#969]
Hello, this issue may be the same as in #372.#415 
![image](https://user-images.githubusercontent.com/38621156/71767138-ed5f9500-2f43-11ea-8cff-5b1e2b5066b0.png)
![image](https://user-images.githubusercontent.com/38621156/71767146-fa7c8400-2f43-11ea-8d82-3d6e0270b72f.png)
I  tried to run the  scikit_bring_your_own(https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own).And I didn't modify the code.
I am confused now . SageMaker is not friendly to green hand.

**Comment by mlcl-peter-holberton** [comment]
I had the same issue on windows.  It seems to be caused by running Docker builds using files with windows line endings.  I solved it by forcing git to keep the unix line endings from the repository, instead of automatically converting them:
`git clone https://github.com/aws/amazon-sagemaker-examples.git --config core.autocrlf=false`

**Comment by celsofranssa** [comment]
Do you have any directions here?
